### ISSUE TITLE
refactor Dataset API

### ISSUE THREAD

**Issue by ConeyLiu** [Intel-bigdata/oap-raydp#55]
Refactor Dataset API into multiple subclasses:

1. GeneralDataset. This class is can process any python object and support any transform functions. And user needs to provide the function to convert the GeneralDataset to torch.data.Dataset or tf.data.Dataset.
2. TextDataset. This class aims to process structure data. Spark is a good choice for processing structure data. So this class is a wrapper of Spark Dataframe.
3. ImageDataset. This class aims to process image data.

Eg:
GeneralDataset
```python
import raydp

general_ds: GeneralDataset = raydp.from_generator(data_generator, num_shards)
# data process

...
def create_torch_ds(ds: GeneralDataset):
    #...
    return torch.data.Dataset(...)

torch_ds = general_ds.to_torch(create_torch_ds)
estimator.fit(torch_ds)
```

TextDataset
```python
import raydp

text_ds: TextDataset = raydp.read_parquet(...)
# data process

...
torch_ds = text_ds.to_torch(...)
estimator.fit(torch_ds)
```

ImageDataset
```python
import raydp

img_ds: ImageDataset = raydp.read_imgs(...)
# data process

...
torch_ds = img_ds.to_torch(...)
estimator.fit(torch_ds)
```

**Comment by ConeyLiu** [comment]
cc @carsonwang, @buaazhwb, any comment for this?

**Comment by carsonwang** [comment]
Is TextDataset a little misleading? sounds like only handle text.

**Comment by ConeyLiu** [comment]
https://github.com/ray-project/ray/pull/11849 has merged into ray upstream. We will use `MLDataset` instead.
