### ISSUE TITLE
[Enhancement] Update Ray version to nightly builds

### ISSUE THREAD

**Issue by wuisawesome** [Intel-bigdata/oap-raydp#78]
Hey there, it looks like Ray's Java API made a backwards incompatible change in December (https://github.com/ray-project/ray/pull/10762). 

Because `RayConfig.instance()` was removed, `spark_init()` breaks at runtime. 

I'm can contribute the change, but wanted to check if this is something the RayDP team is interested in first.

**Comment by ConeyLiu** [comment]
Hi @wuisawesome, it would be very welcome, feel free to submit your fixes.
